Release v0.0.9-BETA (PM 5.0.0)
ReinfyTeam/ProfanityFilter pull request #120
Opened 2023-03-06 13:31 UTC by xqwtxon

**This is an updated version of dev-commit. These needs to be tested in PocketMine-MP 5.0.0 in the future.**

Dylan (dktapps) has announcement about the PocketMine-MP 5.0.0 which supports many advantages of 4.0.0, this release will be able to use to test them to 5.0.0. When its done and ready to publish, we will publish the v0.1.0 which supports 5.0.0 version of PocketMine-MP.

*If you have a question about this pull request, you can comment down below or review this commit.*

2023-03-06 13:32 UTC, xqwtxon commented
Re-updated branch.

2023-03-07 11:51 UTC, NhanAZ submitted a review, later dismissed

2023-03-07 12:13 UTC, Reinfy requested changes

2023-03-07 12:13 UTC, Reinfy commented on build_info.json
> +  "version": "0.0.9",
This should be now `v0.1.0-BETA`

2023-03-07 12:13 UTC, Reinfy commented on build_info.json
>    "channel": "stable",
And the channel must be `BETA`

2023-03-07 12:13 UTC, Reinfy commented on build_info.json
> +  "api_from": "4.0.0",
This should be `4.12.1`

2023-03-07 12:13 UTC, Reinfy commented on build_info.json
> +  "api_to": "4.15.2",
This should be `5.0.0`

2023-03-07 12:13 UTC, Reinfy commented on src/ReinfyTeam/ProfanityFilter/Loader.php
> +		if ((bool) ($this->getConfig()->get("check-updates") ?? true)) {
Why you are checking of a non-nullable function? The function will return false when it is null.

2023-03-07 12:16 UTC, Reinfy commented
Too many code issue stability must be resolved before going to merge this pull request.

2023-03-07 12:25 UTC, Reinfy requested changes

2023-03-07 12:25 UTC, Reinfy commented on src/ReinfyTeam/ProfanityFilter/Loader.php
> +		if (($this->getConfig()->get("check-updates")) {
```suggestion
		if ($this->getConfig()->get("check-updates")) {
```

2023-03-07 12:27 UTC, Reinfy approved these changes

2023-07-30 01:58 UTC, merged